### ISSUE TITLE
dotnet msbuild

### ISSUE THREAD

**Issue by scottdurow** [rajyraman/pcf-template-dataset#1]
Love how your yaml is adaptive and reads the solution and build target! 

Worth considering using the dotnet CLI rather than calling msbuild. The PCF project uses the new SDK format so it doesn't need the VS msbuild.exe

```
    - name: Build
      run: dotnet msbuild "mypcf.cdsproj" /t:build /restore /p:configuration=Release
```

**Comment by rajyraman** [comment]
@scottdurow - That is neat. I did not know that. Thank you Scott.
